name: google-sheet-validator

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - GOOGLE_TOKEN_FILE=/app/data/token.json
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-googlesheet_validator}
      POSTGRES_USER: ${POSTGRES_USER:-validator_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-validator_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: